api:
  image: abprk/flask-apache:latest
  ports:
    - "81:80"
    - "8027:22"
  volumes:
    - ../docroot/api:/var/www/html/
    - ./logs/apache2:/var/log/apache2/
  environment:
    - AUTHORIZED_KEYS="**NONE**"
  links:
    - webapp
webapp:
  image: abprk/reactjs-apache:latest
  ports:
    - "82:80"
    - "8028:22"
  volumes:
    - ../docroot/webapp:/var/www/html/
    - ./logs/apache2:/var/log/apache2/
  environment:
    - AUTHORIZED_KEYS="**NONE**"
# db:
#   image: mysql:5.6
#   mem_limit: 60m
#   entrypoint:
#     - /localdb-run.sh
#   environment:
#     - MYSQL_ROOT_PASSWORD=root
#   volumes:
#     - ./database:/var/lib/mysql/
#     - ./configuration/dev/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
#     - ./logs/mysql:/var/log/mysql/
#     - ./configuration/dev/mysql/localdb-run.sh:/localdb-run.sh
